#!/usr/bin/env bash

iDIR="/usr/share/icons/Yaru"

# Get brightness
get_backlight() {
	echo $(brightnessctl -m | cut -d, -f4)
}

# Get icons
get_icon() {
current=$(get_backlight | sed 's/%//')
        icon="$iDIR/scalable/status/display-brightness-symbolic.svg"
}

# Notify
notify_user() {
        volume=$(brightnessctl -m | cut -d, -f4)
	notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$volume" -u low -i "$icon" "backlight $current%"
}

# Change brightness
change_backlight() {
	brightnessctl set "$1" && get_icon && notify_user
}

# Execute accordingly
case "$1" in
	"--get")
		get_backlight
		;;
	"--inc")
		change_backlight "+10%"
		;;
	"--dec")
		change_backlight "10%-"
		;;
	*)
		get_backlight
		;;
esac
